@host = http://localhost:4400

###

GET {{host}}/api/hello

### 

GET {{host}}/api/good-bye


###

POST {{host}}/api/beverages/coffee

###

POST {{host}}/api/beverages/coffee?sugar=yes

###
POST {{host}}/api/beverages/tea?sugar=yes&milk=yes
Content-Type: application/json

{"kind": "test"}